name: Create Terraform Backend S3

on:
  push:
    paths:
      - 'backend-s3/**'   # ✅ backend-s3 디렉토리 수정 시에만 실행됨

jobs:
  create-backend:
    name: 'Terraform Backend Create'
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-2
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_LOG: DEBUG
      TF_LOG_PATH: terraform-debug.log

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.3

      - name: Terraform Init
        run: |
          cd backend-s3
          terraform init

      - name: Terraform Apply
        run: |
          cd backend-s3
          terraform apply -auto-approve

      - name: Show Terraform Debug Log
        if: always()
        run: |
          echo "====== TF DEBUG LOG ======"
          cat terraform-debug.log || echo "No debug log found"
